name: main

on:
  - push
  - pull_request

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      matrix:
        operating-systems: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13'

      - name: Run tests
        run: make test
